# This workflow demonstrates how to use the Cloud Pub/Sub connector.
# The workflow creates a Pub/Sub topic, a new subscription to that new topic, publishes a new message to
# the topic, pulls the message from the subscription, and then deletes both
# the subscription and the topic.
# Expected successful output: "SUCCESS"

- init:
    assign:
      - project: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
      - topic: "wienerlufttriggertopic"
      - message: {"hello": "trigger"}
      - base64Msg: ${base64.encode(json.encode(message))}
- publish_message_to_topic:
    call: googleapis.pubsub.v1.projects.topics.publish
    args:
      topic: ${"projects/" + project + "/topics/" + topic}
      body:
        messages:
          - data: ${base64Msg}